owner: buligadragos
repo: UpTime

sites:
  - name: Portfolio
    url: https://www.buligadragos.ro
    icon: https://raw.githubusercontent.com/buligadragos/UpTime/master/assets/logo.svg
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  themeUrl: https://cdn.jsdelivr.net/gh/buligadragos/UpTime@master/assets/theme.css
  cname: status.buligadragos.ro
  logoUrl: https://raw.githubusercontent.com/buligadragos/UpTime/master/assets/logo.svg
  name: Status 📈

# Footer
i18n:
  footer: © 2021 [Buliga Dragos](https://buligadragos.ro). All rights reserved.
