# Change these first
owner: buligadragos # Your GitHub organization or username, where this repository lives
repo: UpTime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  themeUrl: https://cdn.jsdelivr.net/gh/buligadragos/UpTime@master/assets/custom-theme.css
  cname: status.buligadragos.ro
  logoUrl: https://raw.githubusercontent.com/buligadragos/UpTime/master/assets/logo.svg
  name: BD - Status 📈

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
