owner: buligadragos
repo: UpTime

sites:
  - name: Portfolio
    url: https://www.buligadragos.ro
    icon: https://raw.githubusercontent.com/buligadragos/portfolio/master/src/images/favicon.png
  - name: GOTO Parking
    url: https://gotoparking.ro
    icon: https://gotoparking.ro/wp-content/uploads/2021/03/cropped-favicon-blk-192x192.png
  - name: Our Collective Experience
    url: http://www.ourcollectiveexperience.com/
    icon: http://www.ourcollectiveexperience.com/images/favicon/favicon-96x96.png
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  themeUrl: https://cdn.jsdelivr.net/gh/buligadragos/UpTime@master/assets/theme.css
  cname: status.buligadragos.ro
  logoUrl: https://raw.githubusercontent.com/buligadragos/UpTime/master/assets/logo.svg
  name: Status 📈

# Footer
i18n:
  footer: © 2021 [Buliga Dragos](https://buligadragos.ro). All rights reserved.
