owner: buligadragos
repo: UpTime

sites:
  - name: Portfolio
    url: https://www.buligadragos.ro
    icon: https://cdn.jsdelivr.net/gh/buligadragos/UpTime@master/assets/favicons/portfolio.png
  - name: GOTO Parking
    url: https://gotoparking.ro
    icon: https://cdn.jsdelivr.net/gh/buligadragos/UpTime@master/assets/favicons/gotoparking.png
  - name: Our Collective Experience
    url: http://www.ourcollectiveexperience.com/
    icon: https://cdn.jsdelivr.net/gh/buligadragos/UpTime@master/assets/favicons/oce.png
  - name: heartMap
    url: https://heartmap.ro/
    icon: https://cdn.jsdelivr.net/gh/buligadragos/UpTime@master/assets/favicons/heartmap.png
  - name: Broken Test
    url: https://broketest.ro/


status-website:
  themeUrl: https://cdn.jsdelivr.net/gh/buligadragos/UpTime@master/assets/theme.css
  cname: status.buligadragos.ro
  logoUrl: https://cdn.jsdelivr.net/gh/buligadragos/UpTime@master/assets/logo.svg
  faviconSvg: https://cdn.jsdelivr.net/gh/buligadragos/UpTime@master/assets/logo.svg
  name: System Status 📈

# Footer
i18n:
  footer: © 2021 [Buliga Dragos](https://buligadragos.ro). All rights reserved.
